/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p4;

import java.awt.Color;

/**
 *
 * @author jacortes
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
        drawMyCanvas.addMouseListener(drawMyCanvas);
        drawMyCanvas.addMouseMotionListener(drawMyCanvas);
    }

    protected enum FIGURE_TYPE {
        OVAL, LINE, SQUARE, CIRCLE,
        ALL;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        figuresButtonGroup = new javax.swing.ButtonGroup();
        colorsButtonGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        figuresPanel = new javax.swing.JPanel();
        dotButton = new javax.swing.JToggleButton();
        lineButton = new javax.swing.JToggleButton();
        squareButton = new javax.swing.JToggleButton();
        ellipseButton = new javax.swing.JToggleButton();
        bottomPanel = new javax.swing.JPanel();
        colorsPanel = new javax.swing.JPanel();
        colorsGroupPanel = new javax.swing.JPanel();
        blackToggleButton = new javax.swing.JToggleButton();
        whiteToggleButton = new javax.swing.JToggleButton();
        blueToggleButton = new javax.swing.JToggleButton();
        yellowToggleButton = new javax.swing.JToggleButton();
        redToggleButton = new javax.swing.JToggleButton();
        greenToggleButton = new javax.swing.JToggleButton();
        colorsOptionPanel = new javax.swing.JPanel();
        fillCheckBox = new javax.swing.JCheckBox();
        statusPanel = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        drawMyCanvas = new p4.MyCanvas();
        topMenuBar = new javax.swing.JMenuBar();
        fileTopMenu = new javax.swing.JMenu();
        newMenuItem = new javax.swing.JMenuItem();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        editTopMenu = new javax.swing.JMenu();
        showMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Basic Paint");

        mainPanel.setLayout(new java.awt.BorderLayout());

        figuresPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        figuresButtonGroup.add(dotButton);
        dotButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p4/Lapiz.gif"))); // NOI18N
        dotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotButtonActionPerformed(evt);
            }
        });
        figuresPanel.add(dotButton);

        figuresButtonGroup.add(lineButton);
        lineButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p4/Linea.gif"))); // NOI18N
        lineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineButtonActionPerformed(evt);
            }
        });
        figuresPanel.add(lineButton);

        figuresButtonGroup.add(squareButton);
        squareButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p4/Rectangulo.gif"))); // NOI18N
        squareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareButtonActionPerformed(evt);
            }
        });
        figuresPanel.add(squareButton);

        figuresButtonGroup.add(ellipseButton);
        ellipseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p4/Ovalo.gif"))); // NOI18N
        ellipseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ellipseButtonActionPerformed(evt);
            }
        });
        figuresPanel.add(ellipseButton);

        mainPanel.add(figuresPanel, java.awt.BorderLayout.PAGE_START);

        bottomPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bottomPanel.setLayout(new java.awt.BorderLayout());

        colorsPanel.setLayout(new java.awt.BorderLayout());

        colorsGroupPanel.setLayout(new java.awt.GridLayout(2, 3, 1, 1));

        blackToggleButton.setBackground(java.awt.Color.black);
        colorsButtonGroup.add(blackToggleButton);
        blackToggleButton.setPreferredSize(new java.awt.Dimension(20, 20));
        blackToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blackToggleButtonActionPerformed(evt);
            }
        });
        colorsGroupPanel.add(blackToggleButton);

        whiteToggleButton.setBackground(new java.awt.Color(255, 255, 255));
        colorsButtonGroup.add(whiteToggleButton);
        whiteToggleButton.setPreferredSize(new java.awt.Dimension(20, 20));
        whiteToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiteToggleButtonActionPerformed(evt);
            }
        });
        colorsGroupPanel.add(whiteToggleButton);

        blueToggleButton.setBackground(java.awt.Color.blue);
        colorsButtonGroup.add(blueToggleButton);
        blueToggleButton.setPreferredSize(new java.awt.Dimension(20, 20));
        blueToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueToggleButtonActionPerformed(evt);
            }
        });
        colorsGroupPanel.add(blueToggleButton);

        yellowToggleButton.setBackground(java.awt.Color.yellow);
        colorsButtonGroup.add(yellowToggleButton);
        yellowToggleButton.setPreferredSize(new java.awt.Dimension(20, 20));
        yellowToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yellowToggleButtonActionPerformed(evt);
            }
        });
        colorsGroupPanel.add(yellowToggleButton);

        redToggleButton.setBackground(java.awt.Color.red);
        colorsButtonGroup.add(redToggleButton);
        redToggleButton.setPreferredSize(new java.awt.Dimension(20, 20));
        redToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redToggleButtonActionPerformed(evt);
            }
        });
        colorsGroupPanel.add(redToggleButton);

        greenToggleButton.setBackground(java.awt.Color.green);
        colorsButtonGroup.add(greenToggleButton);
        greenToggleButton.setPreferredSize(new java.awt.Dimension(20, 20));
        greenToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenToggleButtonActionPerformed(evt);
            }
        });
        colorsGroupPanel.add(greenToggleButton);

        colorsPanel.add(colorsGroupPanel, java.awt.BorderLayout.WEST);

        fillCheckBox.setText("Fill");
        fillCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillCheckBoxActionPerformed(evt);
            }
        });
        colorsOptionPanel.add(fillCheckBox);

        colorsPanel.add(colorsOptionPanel, java.awt.BorderLayout.LINE_END);

        bottomPanel.add(colorsPanel, java.awt.BorderLayout.NORTH);

        statusPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        statusPanel.setLayout(new java.awt.BorderLayout());

        statusLabel.setText("Status label");
        statusPanel.add(statusLabel, java.awt.BorderLayout.PAGE_END);

        bottomPanel.add(statusPanel, java.awt.BorderLayout.SOUTH);

        mainPanel.add(bottomPanel, java.awt.BorderLayout.SOUTH);
        mainPanel.add(drawMyCanvas, java.awt.BorderLayout.CENTER);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        fileTopMenu.setText("File");

        newMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newMenuItem.setText("New");
        fileTopMenu.add(newMenuItem);

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMenuItem.setText("Open");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileTopMenu.add(openMenuItem);

        saveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveMenuItem.setText("Save");
        fileTopMenu.add(saveMenuItem);

        topMenuBar.add(fileTopMenu);

        editTopMenu.setText("Edit");

        showMenuItem.setText("Show Status Bar");
        showMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMenuItemActionPerformed(evt);
            }
        });
        editTopMenu.add(showMenuItem);

        topMenuBar.add(editTopMenu);

        setJMenuBar(topMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void showMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showMenuItemActionPerformed

    private void blueToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueToggleButtonActionPerformed
        drawMyCanvas.setActiveColor(Color.BLUE);
        drawMyCanvas.getActiveFigure().setColor(Color.BLUE);
    }//GEN-LAST:event_blueToggleButtonActionPerformed

    private void redToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redToggleButtonActionPerformed
        drawMyCanvas.setActiveColor(Color.RED);
        drawMyCanvas.getActiveFigure().setColor(Color.RED);
    }//GEN-LAST:event_redToggleButtonActionPerformed

    private void dotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotButtonActionPerformed
        statusLabel.setText("Oval");
        drawMyCanvas.setActiveType(FIGURE_TYPE.OVAL);
        drawMyCanvas.getActiveFigure().setType(FIGURE_TYPE.OVAL);
    }//GEN-LAST:event_dotButtonActionPerformed

    private void squareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareButtonActionPerformed
        statusLabel.setText("Square");
        drawMyCanvas.setActiveType(FIGURE_TYPE.SQUARE);
        drawMyCanvas.getActiveFigure().setType(FIGURE_TYPE.SQUARE);
    }//GEN-LAST:event_squareButtonActionPerformed

    private void fillCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillCheckBoxActionPerformed
        if (fillCheckBox.isSelected()) {
            drawMyCanvas.setIsFilled(true);
            drawMyCanvas.getActiveFigure().setFilled(true);
        } else {
            drawMyCanvas.setIsFilled(false);
            drawMyCanvas.getActiveFigure().setFilled(false);
        }
    }//GEN-LAST:event_fillCheckBoxActionPerformed

    private void blackToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blackToggleButtonActionPerformed
        drawMyCanvas.setActiveColor(Color.BLACK);
        drawMyCanvas.getActiveFigure().setColor(Color.BLACK);
    }//GEN-LAST:event_blackToggleButtonActionPerformed

    private void whiteToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiteToggleButtonActionPerformed
        drawMyCanvas.setActiveColor(Color.WHITE);
        drawMyCanvas.getActiveFigure().setColor(Color.WHITE);
    }//GEN-LAST:event_whiteToggleButtonActionPerformed

    private void yellowToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yellowToggleButtonActionPerformed
        drawMyCanvas.setActiveColor(Color.YELLOW);
        drawMyCanvas.getActiveFigure().setColor(Color.YELLOW);
    }//GEN-LAST:event_yellowToggleButtonActionPerformed

    private void greenToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenToggleButtonActionPerformed
        drawMyCanvas.setActiveColor(Color.GREEN);
        drawMyCanvas.getActiveFigure().setColor(Color.GREEN);
    }//GEN-LAST:event_greenToggleButtonActionPerformed

    private void lineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineButtonActionPerformed
        statusLabel.setText("Line");
        drawMyCanvas.setActiveType(FIGURE_TYPE.LINE);
        drawMyCanvas.getActiveFigure().setType(FIGURE_TYPE.LINE);
    }//GEN-LAST:event_lineButtonActionPerformed

    private void ellipseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ellipseButtonActionPerformed
        statusLabel.setText("Circle");
        drawMyCanvas.setActiveType(FIGURE_TYPE.CIRCLE);
        drawMyCanvas.getActiveFigure().setType(FIGURE_TYPE.CIRCLE);
    }//GEN-LAST:event_ellipseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton blackToggleButton;
    private javax.swing.JToggleButton blueToggleButton;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.ButtonGroup colorsButtonGroup;
    private javax.swing.JPanel colorsGroupPanel;
    private javax.swing.JPanel colorsOptionPanel;
    private javax.swing.JPanel colorsPanel;
    private javax.swing.JToggleButton dotButton;
    private p4.MyCanvas drawMyCanvas;
    private javax.swing.JMenu editTopMenu;
    private javax.swing.JToggleButton ellipseButton;
    private javax.swing.ButtonGroup figuresButtonGroup;
    private javax.swing.JPanel figuresPanel;
    private javax.swing.JMenu fileTopMenu;
    private javax.swing.JCheckBox fillCheckBox;
    private javax.swing.JToggleButton greenToggleButton;
    private javax.swing.JToggleButton lineButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuItem newMenuItem;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JToggleButton redToggleButton;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JMenuItem showMenuItem;
    private javax.swing.JToggleButton squareButton;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JMenuBar topMenuBar;
    private javax.swing.JToggleButton whiteToggleButton;
    private javax.swing.JToggleButton yellowToggleButton;
    // End of variables declaration//GEN-END:variables
}
