/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p4;

/**
 *
 * @author jacortes
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        figuresButtonGroup = new javax.swing.ButtonGroup();
        colorsButtonGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        figuresPanel = new javax.swing.JPanel();
        dotButton = new javax.swing.JToggleButton();
        lineButton = new javax.swing.JToggleButton();
        squareButton = new javax.swing.JToggleButton();
        ellipseButton = new javax.swing.JToggleButton();
        canvasPanel = new javax.swing.JPanel();
        bottomPanel = new javax.swing.JPanel();
        colorsPanel = new javax.swing.JPanel();
        colorsGroupPanel = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        colorsOptionPanel = new javax.swing.JPanel();
        fillCheckBox = new javax.swing.JCheckBox();
        statusPanel = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        topMenuBar = new javax.swing.JMenuBar();
        fileTopMenu = new javax.swing.JMenu();
        newMenuItem = new javax.swing.JMenuItem();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        editTopMenu = new javax.swing.JMenu();
        showMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Basic Paint");

        mainPanel.setLayout(new java.awt.BorderLayout());

        figuresPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        figuresButtonGroup.add(dotButton);
        dotButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p4/Lapiz.gif"))); // NOI18N
        figuresPanel.add(dotButton);

        figuresButtonGroup.add(lineButton);
        lineButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p4/Linea.gif"))); // NOI18N
        figuresPanel.add(lineButton);

        figuresButtonGroup.add(squareButton);
        squareButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p4/Rectangulo.gif"))); // NOI18N
        figuresPanel.add(squareButton);

        figuresButtonGroup.add(ellipseButton);
        ellipseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p4/Ovalo.gif"))); // NOI18N
        figuresPanel.add(ellipseButton);

        mainPanel.add(figuresPanel, java.awt.BorderLayout.PAGE_START);

        canvasPanel.setBackground(new java.awt.Color(255, 255, 255));
        canvasPanel.setPreferredSize(new java.awt.Dimension(200, 200));
        mainPanel.add(canvasPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bottomPanel.setLayout(new java.awt.BorderLayout());

        colorsPanel.setLayout(new java.awt.BorderLayout());

        colorsGroupPanel.setLayout(new java.awt.GridLayout(2, 3, 1, 1));

        jToggleButton1.setBackground(java.awt.Color.black);
        colorsButtonGroup.add(jToggleButton1);
        jToggleButton1.setPreferredSize(new java.awt.Dimension(20, 20));
        colorsGroupPanel.add(jToggleButton1);

        jToggleButton2.setBackground(new java.awt.Color(255, 255, 255));
        colorsButtonGroup.add(jToggleButton2);
        jToggleButton2.setPreferredSize(new java.awt.Dimension(20, 20));
        colorsGroupPanel.add(jToggleButton2);

        jToggleButton6.setBackground(java.awt.Color.blue);
        colorsButtonGroup.add(jToggleButton6);
        jToggleButton6.setPreferredSize(new java.awt.Dimension(20, 20));
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        colorsGroupPanel.add(jToggleButton6);

        jToggleButton5.setBackground(java.awt.Color.yellow);
        colorsButtonGroup.add(jToggleButton5);
        jToggleButton5.setPreferredSize(new java.awt.Dimension(20, 20));
        colorsGroupPanel.add(jToggleButton5);

        jToggleButton4.setBackground(java.awt.Color.red);
        colorsButtonGroup.add(jToggleButton4);
        jToggleButton4.setPreferredSize(new java.awt.Dimension(20, 20));
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        colorsGroupPanel.add(jToggleButton4);

        jToggleButton3.setBackground(java.awt.Color.green);
        colorsButtonGroup.add(jToggleButton3);
        jToggleButton3.setPreferredSize(new java.awt.Dimension(20, 20));
        colorsGroupPanel.add(jToggleButton3);

        colorsPanel.add(colorsGroupPanel, java.awt.BorderLayout.WEST);

        fillCheckBox.setText("Fill");
        colorsOptionPanel.add(fillCheckBox);

        colorsPanel.add(colorsOptionPanel, java.awt.BorderLayout.LINE_END);

        bottomPanel.add(colorsPanel, java.awt.BorderLayout.NORTH);

        statusPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        statusPanel.setLayout(new java.awt.BorderLayout());

        statusLabel.setText("Status label");
        statusPanel.add(statusLabel, java.awt.BorderLayout.PAGE_END);

        bottomPanel.add(statusPanel, java.awt.BorderLayout.SOUTH);

        mainPanel.add(bottomPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        fileTopMenu.setText("File");

        newMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newMenuItem.setText("New");
        fileTopMenu.add(newMenuItem);

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMenuItem.setText("Open");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileTopMenu.add(openMenuItem);

        saveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveMenuItem.setText("Save");
        fileTopMenu.add(saveMenuItem);

        topMenuBar.add(fileTopMenu);

        editTopMenu.setText("Edit");

        showMenuItem.setText("Show Status Bar");
        showMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMenuItemActionPerformed(evt);
            }
        });
        editTopMenu.add(showMenuItem);

        topMenuBar.add(editTopMenu);

        setJMenuBar(topMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void showMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showMenuItemActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel canvasPanel;
    private javax.swing.ButtonGroup colorsButtonGroup;
    private javax.swing.JPanel colorsGroupPanel;
    private javax.swing.JPanel colorsOptionPanel;
    private javax.swing.JPanel colorsPanel;
    private javax.swing.JToggleButton dotButton;
    private javax.swing.JMenu editTopMenu;
    private javax.swing.JToggleButton ellipseButton;
    private javax.swing.ButtonGroup figuresButtonGroup;
    private javax.swing.JPanel figuresPanel;
    private javax.swing.JMenu fileTopMenu;
    private javax.swing.JCheckBox fillCheckBox;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton lineButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuItem newMenuItem;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JMenuItem showMenuItem;
    private javax.swing.JToggleButton squareButton;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JMenuBar topMenuBar;
    // End of variables declaration//GEN-END:variables
}
