/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p3;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;

/**
 *
 * @author jacortes
 */
public class MainWindow extends javax.swing.JFrame {

    Point p = new Point(0, 0);
    Point lineStart = new Point(0, 0);
    Point lineFinish = new Point(0, 0);

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        changeButton = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Events Example");
        addMouseMotionListener(formListener);
        addMouseListener(formListener);

        changeButton.setText("Button");
        changeButton.addMouseMotionListener(formListener);
        changeButton.addMouseListener(formListener);
        changeButton.addActionListener(formListener);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(changeButton)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(changeButton)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.MouseListener, java.awt.event.MouseMotionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == changeButton) {
                MainWindow.this.changeButtonActionPerformed(evt);
            }
        }

        public void mouseClicked(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == MainWindow.this) {
                MainWindow.this.formMouseClicked(evt);
            }
            else if (evt.getSource() == changeButton) {
                MainWindow.this.changeButtonMouseClicked(evt);
            }
        }

        public void mouseEntered(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == changeButton) {
                MainWindow.this.changeButtonMouseEntered(evt);
            }
        }

        public void mouseExited(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == changeButton) {
                MainWindow.this.changeButtonMouseExited(evt);
            }
        }

        public void mousePressed(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == MainWindow.this) {
                MainWindow.this.formMousePressed(evt);
            }
        }

        public void mouseReleased(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == MainWindow.this) {
                MainWindow.this.formMouseReleased(evt);
            }
        }

        public void mouseDragged(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == changeButton) {
                MainWindow.this.changeButtonMouseDragged(evt);
            }
            else if (evt.getSource() == MainWindow.this) {
                MainWindow.this.formMouseDragged(evt);
            }
        }

        public void mouseMoved(java.awt.event.MouseEvent evt) {
        }
    }// </editor-fold>//GEN-END:initComponents
    public void paint(Graphics g) {
        super.paint(g);
        g.fillOval(p.x - 5, p.y - 5, 10, 10);
        g.drawLine(lineStart.x, lineStart.y, lineFinish.x, lineFinish.y);
    }
    private void changeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeButtonMouseClicked
        changeButton.setBackground(Color.red);
    }//GEN-LAST:event_changeButtonMouseClicked

    private void changeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeButtonMouseEntered
        changeButton.setBackground(Color.green);
    }//GEN-LAST:event_changeButtonMouseEntered

    private void changeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeButtonMouseExited
        changeButton.setBackground(Color.blue);
    }//GEN-LAST:event_changeButtonMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        this.setTitle("Mouse clicked :D");
        p = evt.getPoint();
        this.repaint();
    }//GEN-LAST:event_formMouseClicked

    private void changeButtonMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeButtonMouseDragged
        changeButton.setBackground(Color.yellow);
    }//GEN-LAST:event_changeButtonMouseDragged

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        changeButton.setBackground(Color.orange);
    }//GEN-LAST:event_changeButtonActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        lineStart = evt.getPoint();
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        lineFinish = evt.getPoint();
        this.repaint();
    }//GEN-LAST:event_formMouseReleased

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        lineFinish = evt.getPoint();
        this.repaint();
    }//GEN-LAST:event_formMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeButton;
    // End of variables declaration//GEN-END:variables
}
